'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import '@mantine/core/styles.css'
import { MantineProvider } from '@mantine/core'
import {AuthContextProvider} from "../context/authContext";
import  Navbar from '../components/navbar';
import  LeftBar from '../components/leftbar';
import  RightBar from '../components/rightbar';

const inter = Inter({ subsets: ['latin'] })
/*
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({ children }) {
  return (
  
      
          <html lang='en'>
      <body className={inter.className}>
      <AuthContextProvider>
        <MantineProvider>
      <Navbar />
      <div style={{ display: "flex" }}>
        <LeftBar />
        <div style={{ flex: 6 }}>
         {children}
        </div>
        <RightBar />
        </div>
        </MantineProvider>
      </AuthContextProvider>
      </body>
    </html>
  
  )
}
